"""feat: enterprises, floor_plans e units

Revision ID: 3af34cbcffb3
Revises: f8816dd6496a
Create Date: 2026-03-19 21:52:21.566324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af34cbcffb3'
down_revision: Union[str, None] = 'f8816dd6496a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('delivery_forecast', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('LANCAMENTO', 'EM_CONSTRUCAO', 'PRONTO', name='enterprisestatus'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_city'), 'enterprises', ['city'], unique=False)
    op.create_index(op.f('ix_enterprises_is_active'), 'enterprises', ['is_active'], unique=False)
    op.create_index(op.f('ix_enterprises_owner_id'), 'enterprises', ['owner_id'], unique=False)
    op.create_index(op.f('ix_enterprises_state'), 'enterprises', ['state'], unique=False)
    op.create_index(op.f('ix_enterprises_status'), 'enterprises', ['status'], unique=False)
    op.create_table('floor_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('broker_commission', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floor_plans_enterprise_id'), 'floor_plans', ['enterprise_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'VENDIDO', name='unitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_enterprise_id'), 'units', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_units_floor_plan_id'), 'units', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.add_column('proposals', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.alter_column('proposals', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_proposals_unit_id'), 'proposals', ['unit_id'], unique=False)
    op.create_foreign_key(None, 'proposals', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_index(op.f('ix_proposals_unit_id'), table_name='proposals')
    op.alter_column('proposals', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('proposals', 'unit_id')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_floor_plan_id'), table_name='units')
    op.drop_index(op.f('ix_units_enterprise_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_floor_plans_enterprise_id'), table_name='floor_plans')
    op.drop_table('floor_plans')
    op.drop_index(op.f('ix_enterprises_status'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_state'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_owner_id'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_is_active'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_city'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
