"""initial

Revision ID: f8816dd6496a
Revises: 
Create Date: 2026-03-08 10:07:46.302312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8816dd6496a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('creci_number', sa.String(length=50), nullable=True),
    sa.Column('user_type', sa.Enum('CONSTRUTORA', 'CORRETOR', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.Enum('APARTAMENTO', 'CASA', 'COBERTURA', 'SOBRADO', 'LOFT', 'TERRENO', 'COMERCIAL', name='propertytype'), nullable=False),
    sa.Column('transaction_type', sa.Enum('VENDA', 'ALUGUEL', 'TEMPORADA', name='transactiontype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index(op.f('ix_properties_transaction_type'), 'properties', ['transaction_type'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('corretor_id', sa.UUID(), nullable=False),
    sa.Column('client_full_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('client_cpf', sa.String(length=14), nullable=False),
    sa.Column('client_rg', sa.String(length=20), nullable=False),
    sa.Column('client_birthdate', sa.String(length=10), nullable=False),
    sa.Column('client_marital_status', sa.String(length=50), nullable=False),
    sa.Column('client_profession', sa.String(length=100), nullable=False),
    sa.Column('client_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('client_zip_code', sa.String(length=20), nullable=False),
    sa.Column('client_address', sa.String(length=255), nullable=False),
    sa.Column('client_number', sa.String(length=10), nullable=False),
    sa.Column('client_complement', sa.String(length=100), nullable=True),
    sa.Column('client_neighborhood', sa.String(length=100), nullable=False),
    sa.Column('client_city', sa.String(length=100), nullable=False),
    sa.Column('client_state', sa.String(length=5), nullable=False),
    sa.Column('offered_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('A_VISTA', 'FINANCIAMENTO', 'PERMUTA', 'OUTRO', name='paymenttype'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_NEGOCIACAO', 'ACEITA', 'RECUSADA', name='proposalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corretor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_corretor_id'), 'proposals', ['corretor_id'], unique=False)
    op.create_index(op.f('ix_proposals_property_id'), 'proposals', ['property_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_table('proposal_negotiations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('offered_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('A_VISTA', 'FINANCIAMENTO', 'PERMUTA', 'OUTRO', name='paymenttype'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_negotiations_proposal_id'), 'proposal_negotiations', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_negotiations_proposal_id'), table_name='proposal_negotiations')
    op.drop_table('proposal_negotiations')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_property_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_corretor_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_properties_transaction_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
